### ISSUE TITLE
Extract shared inputs/outputs for exercise Hexadecimal

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#101]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `hexadecimal.json` containing the inputs and expected outputs for Hexadecimal.

Hexadecimal has been implemented in the following languages:
- https://github.com/exercism/xclojure/tree/master/hexadecimal
- https://github.com/exercism/xcoffeescript/tree/master/hexadecimal
- https://github.com/exercism/xcpp/tree/master/hexadecimal
- https://github.com/exercism/xcsharp/tree/master/hexadecimal
- https://github.com/exercism/xgo/tree/master/hexadecimal
- https://github.com/exercism/xhaskell/tree/master/hexadecimal
- https://github.com/exercism/xjavascript/tree/master/hexadecimal
- https://github.com/exercism/xocaml/tree/master/hexadecimal
- https://github.com/exercism/xperl5/tree/master/hexadecimal
- https://github.com/exercism/xpython/tree/master/hexadecimal
- https://github.com/exercism/xruby/tree/master/hexadecimal
- https://github.com/exercism/xrust/tree/master/hexadecimal
- https://github.com/exercism/xscala/tree/master/hexadecimal

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
We would like to deprecate the hexadecimal exercise in favour of All Your Base: https://github.com/exercism/x-common/issues/279

Given this, canonical data for the hexadecimal exercise should be considered a very low priority; consider working on another problem first.

If we actually do deprecate the hexadecimal exercise, it is okay if there is no canonical data and this issue should be closed.

**Comment by kytrinyx** [comment]
I agree. We should close it. Thank you, @petertseng
