### ISSUE TITLE
Extract shared inputs/outputs for exercise Largest Series Product

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#104]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `largest-series-product.json` containing the inputs and expected outputs for Largest Series Product.

Largest Series Product has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/largest-series-product
- https://github.com/exercism/xcsharp/tree/master/largest-series-product
- https://github.com/exercism/xelixir/tree/master/largest-series-product
- https://github.com/exercism/xerlang/tree/master/largest-series-product
- https://github.com/exercism/xgo/tree/master/largest-series-product
- https://github.com/exercism/xhaskell/tree/master/largest-series-product
- https://github.com/exercism/xjavascript/tree/master/largest-series-product
- https://github.com/exercism/xlfe/tree/master/largest-series-product
- https://github.com/exercism/xperl5/tree/master/largest-series-product
- https://github.com/exercism/xpython/tree/master/largest-series-product
- https://github.com/exercism/xruby/tree/master/largest-series-product
- https://github.com/exercism/xscala/tree/master/largest-series-product

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Starting work on this. Note that a new language has implemented LSP since this issue was created:

https://github.com/exercism/xecmascript/tree/master/largest-series-product

**Comment by petertseng** [comment]
Gonna use this as a place to keep some notes.

list:
http://x.exercism.io/problems/largest-series-product

go moved its exercises to subdir, so I need to be able to edit the list.

* https://github.com/exercism/xclojure/tree/master/largest-series-product
* https://github.com/exercism/xcsharp/tree/master/largest-series-product
* https://github.com/exercism/xecmascript/tree/master/largest-series-product
* https://github.com/exercism/xelixir/tree/master/largest-series-product
* https://github.com/exercism/xerlang/tree/master/largest-series-product
* https://github.com/exercism/xgo/tree/master/exercises/largest-series-product
* https://github.com/exercism/xhaskell/tree/master/largest-series-product
* https://github.com/exercism/xjavascript/tree/master/largest-series-product
* https://github.com/exercism/xlfe/tree/master/largest-series-product
* https://github.com/exercism/xperl5/tree/master/largest-series-product
* https://github.com/exercism/xpython/tree/master/largest-series-product
* https://github.com/exercism/xruby/tree/master/largest-series-product
* https://github.com/exercism/xscala/tree/master/largest-series-product
