### ISSUE TITLE
Extract shared inputs/outputs for exercise List Ops

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#109]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `list-ops.json` containing the inputs and expected outputs for List Ops.

List Ops has been implemented in the following languages:
- https://github.com/exercism/xelixir/tree/master/list-ops
- https://github.com/exercism/xhaskell/tree/master/list-ops
- https://github.com/exercism/xocaml/tree/master/list-ops
- https://github.com/exercism/xperl5/tree/master/list-ops
- https://github.com/exercism/xscheme/tree/master/list-ops

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by bunnymatic** [comment]
I'll try this one. 

I'll use this discussion point (https://github.com/exercism/todo/issues/152#issuecomment-275889363) for the first cut at function representations.
