### ISSUE TITLE
Extract shared inputs/outputs for exercise Luhn

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#110]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `luhn.json` containing the inputs and expected outputs for Luhn.

Luhn has been implemented in the following languages:

- https://github.com/exercism/xcoffeescript/tree/master/luhn
- https://github.com/exercism/xcsharp/tree/master/luhn
- https://github.com/exercism/xerlang/tree/master/luhn
- https://github.com/exercism/xfsharp/tree/master/luhn
- https://github.com/exercism/xgo/tree/master/luhn
- https://github.com/exercism/xhaskell/tree/master/luhn
- https://github.com/exercism/xjava/tree/master/luhn
- https://github.com/exercism/xjavascript/tree/master/luhn
- https://github.com/exercism/xlfe/tree/master/luhn
- https://github.com/exercism/xocaml/tree/master/luhn
- https://github.com/exercism/xperl5/tree/master/luhn
- https://github.com/exercism/xpython/tree/master/luhn
- https://github.com/exercism/xruby/tree/master/luhn
- https://github.com/exercism/xscala/tree/master/luhn
- https://github.com/exercism/xswift/tree/master/luhn

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by kytrinyx** [comment]
Note: most of the tracks moved their exercises to a subdirectory named "exercises" so if you get a 404 on any of the links, try the same link with `/exercises/` inserted before the problem name.

**Comment by oalbe** [comment]
Here we are, I think I made it.

Just a few clarifications:  
Since, as discussed [here](https://github.com/exercism/xpython/issues/284), there were some incomprehensions about what results should have actually returned the checksum control. I did some research and found out that basically the results in the Python track are wrong.

According to one of the external resources offered by Wikipedia, the exact results are the ones present, for example, in the JavaScript track. To prove this I actually slightly modified the `luhn.c` implementation of the algorithm listed in the external resources of [this](https://en.wikipedia.org/wiki/Luhn_algorithm) article in order to make it print also the computed checksum.

There's to say, though, that an online converter found googling actually returned the same values (`2` and `1`) present in the Python testfile, but here I am taking Wikipedia and @behrtam's comment as sources of truth and sticking with that.

Here's the `luhn.json` file I came up with:

```json
{
   "#": [
     "The only note about this exercise is to make sure that the methods used",
     "to check if a number is valid and to compute its checksum DO NOT modify",
     "the value of the internal attributes.  ",
     "I say this because I've seen for the Python testcases that it needs a last",
     "test to call the validation method twice to assure this.  ",
     "Simply assure that the two methods are const methods (to use a C++ notation)",
     "using the tools available in your language.  ",
     "Here is a pretty universal solution for the validation method:  ",
     "`return (0 === (this.checksum % 10)) ? true : false;`"
   ],
   "cases": [
      {
         "description": "check digit",
         "input": 34567,
         "expected": 7,
         "msg": "The check digit is 7."
      },
      {
         "description": "check digit with input ending in zero",
         "input": 91370,
         "expected": 0,
         "msg": "The check digit is 0."
      },
      {
         "description": "check addends",
         "input": 12121,
         "expected": [1, 4, 1, 4, 1],
         "msg": "The parsed addends form the array of integers: [1, 4, 1, 4, 1]."
      },
      {
         "description": "check too large addends",
         "input": 8631,
         "expected": [7, 6, 6, 1],
         "msg": "The parsed addends form the array of integers: [7, 6, 6, 1]."
      },
      {
         "description": "checksum",
         "input": 4913,
         "expected": 22,
         "msg": "The checksum is 22."
      },
      {
         "description": "checksum of larger number",
         "input": 201773,
         "expected": 21,
         "msg": "The checksum is 21."
      },
      {
         "description": "check invalid number",
         "input": 738,
         "expected": false,
         "msg": "The input is NOT a valid Luhn number."
      },
      {
         "description": "check valid number",
         "input": 8739567,
         "expected": true,
         "msg": "The input is a valid Luhn number."
      },
      {
         "description": "create valid number",
         "input": 123,
         "expected": 1230,
         "msg": "The created number is 1230."
      },
      {
         "description": "create larger valid number",
         "input": 873956,
         "expected": 8739567,
         "msg": "The created number is 8739567."
      },
      {
         "description": "create even larger valid number",
         "input": 837263756,
         "expected": 8372637564,
         "msg": "The created number is 8372637564."
      }
   ]
}
```

Please, let me know if I did something wrong.

P.S.: In `hamming.json`'s first section (the one named `"#"`) there's a typo on line 9. _languge_ instead of _langu**a**ge_.

**Comment by kytrinyx** [comment]
This looks excellent! Do you have time to submit that json file in a PR to https://github.com/exercism/x-common?

Thanks for the heads up on the typo. Fixed in 51e8d2767e36e1b42b9252f4d7dfc183f6edf621

**Comment by kytrinyx** [comment]
I removed the 'msg' key in the hamming.json in exercism/x-common@1483fe9fafcc74f9e09b518cf0de9065047d3eb7

**Comment by oalbe** [comment]
> This looks excellent! You can ditch the "msg" key, we've moved away from supplying those.
> Do you have time to submit that json file in a PR to https://github.com/exercism/x-common?

Yep, going to do that now. Let's see if I manage to mess this too.

**Comment by kytrinyx** [comment]
w00t, thanks!
