### ISSUE TITLE
Extract shared inputs/outputs for exercise Nth Prime

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#114]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `nth-prime.json` containing the inputs and expected outputs for Nth Prime.

Nth Prime has been implemented in the following languages:

- https://github.com/exercism/xcoffeescript/tree/master/nth-prime
- https://github.com/exercism/xcpp/tree/master/nth-prime
- https://github.com/exercism/xelixir/tree/master/nth-prime
- https://github.com/exercism/xgo/tree/master/nth-prime
- https://github.com/exercism/xhaskell/tree/master/nth-prime
- https://github.com/exercism/xjavascript/tree/master/nth-prime
- https://github.com/exercism/xplsql/tree/master/nth-prime
- https://github.com/exercism/xpython/tree/master/nth-prime
- https://github.com/exercism/xruby/tree/master/nth-prime
- https://github.com/exercism/xscala/tree/master/nth-prime

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
completed by https://github.com/exercism/x-common/pull/332
