### ISSUE TITLE
Extract shared inputs/outputs for exercise Nucleotide Codons

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#115]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `nucleotide-codons.json` containing the inputs and expected outputs for Nucleotide Codons.

Nucleotide Codons has been implemented in the following languages:
- https://github.com/exercism/xrust/tree/master/nucleotide-codons

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
https://github.com/exercism/x-common/issues/268 has nominated nucleotide-codons for deprecation in favour of protein translation. Protein translation also has an issue for a JSON file, #130. It is probably not worth it to write canonical data for nucleotide-codons.
