### ISSUE TITLE
Extract shared inputs/outputs for exercise Nucleotide Count

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#116]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `nucleotide-count.json` containing the inputs and expected outputs for Nucleotide Count.

Nucleotide Count has been implemented in the following languages:
- https://github.com/exercism/xclojure/tree/master/nucleotide-count
- https://github.com/exercism/xcoffeescript/tree/master/nucleotide-count
- https://github.com/exercism/xcpp/tree/master/nucleotide-count
- https://github.com/exercism/xcsharp/tree/master/nucleotide-count
- https://github.com/exercism/xelixir/tree/master/nucleotide-count
- https://github.com/exercism/xerlang/tree/master/nucleotide-count
- https://github.com/exercism/xgo/tree/master/nucleotide-count
- https://github.com/exercism/xhaskell/tree/master/nucleotide-count
- https://github.com/exercism/xjava/tree/master/nucleotide-count
- https://github.com/exercism/xlfe/tree/master/nucleotide-count
- https://github.com/exercism/xlisp/tree/master/nucleotide-count
- https://github.com/exercism/xlua/tree/master/nucleotide-count
- https://github.com/exercism/xobjective-c/tree/master/nucleotide-count
- https://github.com/exercism/xocaml/tree/master/nucleotide-count
- https://github.com/exercism/xperl5/tree/master/nucleotide-count
- https://github.com/exercism/xruby/tree/master/nucleotide-count
- https://github.com/exercism/xrust/tree/master/nucleotide-count
- https://github.com/exercism/xscala/tree/master/nucleotide-count
- https://github.com/exercism/xscheme/tree/master/nucleotide-count
- https://github.com/exercism/xswift/tree/master/nucleotide-count

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by bunnymatic** [comment]
I'm going to try working on getting the shared test data files ready for nucleotide-count.

**Comment by bunnymatic** [comment]
Here's the work https://github.com/exercism/x-common/pull/505.  The PR has been approved and when merged should allow us to close this guy
