### ISSUE TITLE
Extract shared inputs/outputs for exercise Ocr Numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#117]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `ocr-numbers.json` containing the inputs and expected outputs for Ocr Numbers.

Ocr Numbers has been implemented in the following languages:

- https://github.com/exercism/xgo/tree/master/ocr-numbers
- https://github.com/exercism/xhaskell/tree/master/ocr-numbers
- https://github.com/exercism/xjavascript/tree/master/ocr-numbers
- https://github.com/exercism/xperl5/tree/master/ocr-numbers
- https://github.com/exercism/xpython/tree/master/ocr-numbers
- https://github.com/exercism/xruby/tree/master/ocr-numbers
- https://github.com/exercism/xscala/tree/master/ocr-numbers

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
completed in https://github.com/exercism/x-common/pull/291
