### ISSUE TITLE
Extract shared inputs/outputs for exercise Octal

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#118]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `octal.json` containing the inputs and expected outputs for Octal.

Octal has been implemented in the following languages:
- https://github.com/exercism/xcsharp/tree/master/octal
- https://github.com/exercism/xfsharp/tree/master/octal
- https://github.com/exercism/xgo/tree/master/octal
- https://github.com/exercism/xhaskell/tree/master/octal
- https://github.com/exercism/xjava/tree/master/octal
- https://github.com/exercism/xjavascript/tree/master/octal
- https://github.com/exercism/xscala/tree/master/octal
- https://github.com/exercism/xswift/tree/master/octal

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
We would like to deprecate the octal exercise in favour of All Your Base: https://github.com/exercism/x-common/issues/279

Given this, canonical data for the octal exercise should be considered a very low priority; consider working on another problem first.

If we actually do deprecate the octal exercise, it is okay if there is no canonical data and this issue should be closed.

**Comment by kytrinyx** [comment]
Agreed, thanks.
