### ISSUE TITLE
Extract shared inputs/outputs for exercise Pascals Triangle

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#122]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `pascals-triangle.json` containing the inputs and expected outputs for Pascals Triangle.

Pascals Triangle has been implemented in the following languages:

- https://github.com/exercism/xcoffeescript/tree/master/pascals-triangle
- https://github.com/exercism/xgo/tree/master/pascals-triangle
- https://github.com/exercism/xhaskell/tree/master/pascals-triangle
- https://github.com/exercism/xjava/tree/master/pascals-triangle
- https://github.com/exercism/xjavascript/tree/master/pascals-triangle
- https://github.com/exercism/xperl5/tree/master/pascals-triangle
- https://github.com/exercism/xruby/tree/master/pascals-triangle
- https://github.com/exercism/xscala/tree/master/pascals-triangle

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
completed in https://github.com/exercism/x-common/pull/362
