### ISSUE TITLE
Extract shared inputs/outputs for exercise Pig Latin

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#125]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `pig-latin.json` containing the inputs and expected outputs for Pig Latin.

Pig Latin has been implemented in the following languages:

- https://github.com/exercism/xcsharp/tree/master/pig-latin
- https://github.com/exercism/xfsharp/tree/master/pig-latin
- https://github.com/exercism/xgo/tree/master/pig-latin
- https://github.com/exercism/xhaskell/tree/master/pig-latin
- https://github.com/exercism/xjava/tree/master/pig-latin
- https://github.com/exercism/xjavascript/tree/master/pig-latin
- https://github.com/exercism/xperl5/tree/master/pig-latin
- https://github.com/exercism/xruby/tree/master/pig-latin
- https://github.com/exercism/xscala/tree/master/pig-latin
- https://github.com/exercism/xswift/tree/master/pig-latin

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Good to merge since the already-linked PR is merged
