### ISSUE TITLE
Extract shared inputs/outputs for exercise Point Mutations

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#126]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `point-mutations.json` containing the inputs and expected outputs for Point Mutations.

Point Mutations has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/point-mutations
- https://github.com/exercism/xelisp/tree/master/point-mutations
- https://github.com/exercism/xelixir/tree/master/point-mutations
- https://github.com/exercism/xerlang/tree/master/point-mutations
- https://github.com/exercism/xhaskell/tree/master/point-mutations
- https://github.com/exercism/xlfe/tree/master/point-mutations
- https://github.com/exercism/xlisp/tree/master/point-mutations
- https://github.com/exercism/xocaml/tree/master/point-mutations
- https://github.com/exercism/xrust/tree/master/point-mutations
- https://github.com/exercism/xscheme/tree/master/point-mutations

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Point mutations will be deprecated https://github.com/exercism/x-common/issues/384 thus we do not need to add shared data for it.
