### ISSUE TITLE
Extract shared inputs/outputs for exercise Prime Factors

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#129]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `prime-factors.json` containing the inputs and expected outputs for Prime Factors.

Prime Factors has been implemented in the following languages:
- https://github.com/exercism/xclojure/tree/master/prime-factors
- https://github.com/exercism/xcpp/tree/master/prime-factors
- https://github.com/exercism/xcsharp/tree/master/prime-factors
- https://github.com/exercism/xelixir/tree/master/prime-factors
- https://github.com/exercism/xgo/tree/master/prime-factors
- https://github.com/exercism/xhaskell/tree/master/prime-factors
- https://github.com/exercism/xjava/tree/master/prime-factors
- https://github.com/exercism/xjavascript/tree/master/prime-factors
- https://github.com/exercism/xlisp/tree/master/prime-factors
- https://github.com/exercism/xlua/tree/master/prime-factors
- https://github.com/exercism/xocaml/tree/master/prime-factors
- https://github.com/exercism/xperl5/tree/master/prime-factors
- https://github.com/exercism/xpython/tree/master/prime-factors
- https://github.com/exercism/xruby/tree/master/prime-factors
- https://github.com/exercism/xscala/tree/master/prime-factors
- https://github.com/exercism/xswift/tree/master/prime-factors

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by bunnymatic** [comment]
I'll try this one.
