### ISSUE TITLE
Extract shared inputs/outputs for exercise Pythagorean Triplet

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#132]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `pythagorean-triplet.json` containing the inputs and expected outputs for Pythagorean Triplet.

Pythagorean Triplet has been implemented in the following languages:
- https://github.com/exercism/xcsharp/tree/master/pythagorean-triplet
- https://github.com/exercism/xelixir/tree/master/pythagorean-triplet
- https://github.com/exercism/xgo/tree/master/pythagorean-triplet
- https://github.com/exercism/xhaskell/tree/master/pythagorean-triplet
- https://github.com/exercism/xjavascript/tree/master/pythagorean-triplet
- https://github.com/exercism/xperl5/tree/master/pythagorean-triplet
- https://github.com/exercism/xpython/tree/master/pythagorean-triplet
- https://github.com/exercism/xruby/tree/master/pythagorean-triplet
- https://github.com/exercism/xscala/tree/master/pythagorean-triplet
- https://github.com/exercism/xswift/tree/master/pythagorean-triplet

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by wobh** [comment]
I've been meaning to file a ticket but I think it would help to change the tests for this exercise to guide the student implementing Euclid's algorithm.

**Comment by kytrinyx** [comment]
I think you're right. Do you have any suggestions for the approach to take?

**Comment by wobh** [comment]
I do, or rather, I will when I focus on this again, possibly in a couple weeks.

**Comment by kytrinyx** [comment]
Understood! Thanks.

**Comment by kytrinyx** [comment]
Find up to date issue here: https://github.com/exercism/x-common/issues/552
