### ISSUE TITLE
Extract shared inputs/outputs for exercise Robot Simulator

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#139]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `robot-simulator.json` containing the inputs and expected outputs for Robot Simulator.

Robot Simulator has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/robot-simulator
- https://github.com/exercism/xerlang/tree/master/robot-simulator
- https://github.com/exercism/xgo/tree/master/robot-simulator
- https://github.com/exercism/xhaskell/tree/master/robot-simulator
- https://github.com/exercism/xjavascript/tree/master/robot-simulator
- https://github.com/exercism/xlfe/tree/master/robot-simulator
- https://github.com/exercism/xperl5/tree/master/robot-simulator
- https://github.com/exercism/xpython/tree/master/robot-simulator
- https://github.com/exercism/xruby/tree/master/robot-simulator
- https://github.com/exercism/xscala/tree/master/robot-simulator

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
closed by https://github.com/exercism/x-common/pull/282
