### ISSUE TITLE
Extract shared inputs/outputs for exercise Scrabble Score

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#144]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `scrabble-score.json` containing the inputs and expected outputs for Scrabble Score.

Scrabble Score has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/scrabble-score
- https://github.com/exercism/xcpp/tree/master/scrabble-score
- https://github.com/exercism/xcsharp/tree/master/scrabble-score
- https://github.com/exercism/xecmascript/tree/master/scrabble-score
- https://github.com/exercism/xelixir/tree/master/scrabble-score
- https://github.com/exercism/xfsharp/tree/master/scrabble-score
- https://github.com/exercism/xgo/tree/master/scrabble-score
- https://github.com/exercism/xhaskell/tree/master/scrabble-score
- https://github.com/exercism/xjava/tree/master/scrabble-score
- https://github.com/exercism/xjavascript/tree/master/scrabble-score
- https://github.com/exercism/xlisp/tree/master/scrabble-score
- https://github.com/exercism/xlua/tree/master/scrabble-score
- https://github.com/exercism/xperl5/tree/master/scrabble-score
- https://github.com/exercism/xpython/tree/master/scrabble-score
- https://github.com/exercism/xruby/tree/master/scrabble-score
- https://github.com/exercism/xscala/tree/master/scrabble-score
- https://github.com/exercism/xswift/tree/master/scrabble-score

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Note, in flight at https://github.com/exercism/x-common/pull/161

**Comment by petertseng** [comment]
Closed by https://github.com/exercism/x-common/pull/255
