### ISSUE TITLE
Extract shared inputs/outputs for exercise Secret Handshake

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#145]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `secret-handshake.json` containing the inputs and expected outputs for Secret Handshake.

Secret Handshake has been implemented in the following languages:
- https://github.com/exercism/xcsharp/tree/master/secret-handshake
- https://github.com/exercism/xgo/tree/master/secret-handshake
- https://github.com/exercism/xhaskell/tree/master/secret-handshake
- https://github.com/exercism/xjavascript/tree/master/secret-handshake
- https://github.com/exercism/xperl5/tree/master/secret-handshake
- https://github.com/exercism/xpython/tree/master/secret-handshake
- https://github.com/exercism/xruby/tree/master/secret-handshake
- https://github.com/exercism/xscala/tree/master/secret-handshake
- https://github.com/exercism/xswift/tree/master/secret-handshake

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by abeger** [comment]
Decided to go for this one.

**Comment by abeger** [comment]
Hm. The Python test adds a whole different set of tests and a whole new function call: instead of just implementing `handshake`, which converts a number to gestures, it also includes `code`, which reverses the process. 

I think I'll include both and let the implementors decide if they want `code` or not.

**Comment by kytrinyx** [comment]
That sounds like a good call.  Thanks.
