### ISSUE TITLE
Extract shared inputs/outputs for exercise Sieve

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#148]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `sieve.json` containing the inputs and expected outputs for Sieve.

Sieve has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/sieve
- https://github.com/exercism/xcpp/tree/master/sieve
- https://github.com/exercism/xcsharp/tree/master/sieve
- https://github.com/exercism/xelixir/tree/master/sieve
- https://github.com/exercism/xgo/tree/master/sieve
- https://github.com/exercism/xhaskell/tree/master/sieve
- https://github.com/exercism/xjava/tree/master/sieve
- https://github.com/exercism/xjavascript/tree/master/sieve
- https://github.com/exercism/xlisp/tree/master/sieve
- https://github.com/exercism/xperl5/tree/master/sieve
- https://github.com/exercism/xpython/tree/master/sieve
- https://github.com/exercism/xruby/tree/master/sieve
- https://github.com/exercism/xscala/tree/master/sieve
- https://github.com/exercism/xswift/tree/master/sieve

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by abeger** [comment]
I'll take a stab at this.

**Comment by abeger** [comment]
Pull request submitted. When/if this gets accepted, I hope to go hog wild on these JSON tickets.

**Comment by kytrinyx** [comment]
Yay, thank you!
