### ISSUE TITLE
Extract shared inputs/outputs for exercise Space Age

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#151]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `space-age.json` containing the inputs and expected outputs for Space Age.

Space Age has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/space-age
- https://github.com/exercism/xcpp/tree/master/space-age
- https://github.com/exercism/xcsharp/tree/master/space-age
- https://github.com/exercism/xecmascript/tree/master/space-age
- https://github.com/exercism/xelixir/tree/master/space-age
- https://github.com/exercism/xerlang/tree/master/space-age
- https://github.com/exercism/xfsharp/tree/master/space-age
- https://github.com/exercism/xhaskell/tree/master/space-age
- https://github.com/exercism/xjava/tree/master/space-age
- https://github.com/exercism/xjavascript/tree/master/space-age
- https://github.com/exercism/xlfe/tree/master/space-age
- https://github.com/exercism/xlisp/tree/master/space-age
- https://github.com/exercism/xlua/tree/master/space-age
- https://github.com/exercism/xocaml/tree/master/space-age
- https://github.com/exercism/xperl5/tree/master/space-age
- https://github.com/exercism/xpython/tree/master/space-age
- https://github.com/exercism/xruby/tree/master/space-age
- https://github.com/exercism/xscala/tree/master/space-age
- https://github.com/exercism/xswift/tree/master/space-age

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Closed by https://github.com/exercism/x-common/pull/256
