### ISSUE TITLE
Extract shared inputs/outputs for exercise Sublist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#153]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `sublist.json` containing the inputs and expected outputs for Sublist.

Sublist has been implemented in the following languages:

- https://github.com/exercism/xelixir/tree/master/sublist
- https://github.com/exercism/xhaskell/tree/master/sublist
- https://github.com/exercism/xperl5/tree/master/sublist
- https://github.com/exercism/xpython/tree/master/sublist
- https://github.com/exercism/xscala/tree/master/sublist

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
In flight at https://github.com/exercism/x-common/pull/227

**Comment by petertseng** [comment]
That PR was merged. Closed.
