### ISSUE TITLE
Extract shared inputs/outputs for exercise Sum Of Multiples

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#154]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `sum-of-multiples.json` containing the inputs and expected outputs for Sum Of Multiples.

Sum Of Multiples has been implemented in the following languages:

- https://github.com/exercism/xcpp/tree/master/sum-of-multiples
- https://github.com/exercism/xcsharp/tree/master/sum-of-multiples
- https://github.com/exercism/xelixir/tree/master/sum-of-multiples
- https://github.com/exercism/xerlang/tree/master/sum-of-multiples
- https://github.com/exercism/xfsharp/tree/master/sum-of-multiples
- https://github.com/exercism/xgo/tree/master/sum-of-multiples
- https://github.com/exercism/xhaskell/tree/master/sum-of-multiples
- https://github.com/exercism/xjavascript/tree/master/sum-of-multiples
- https://github.com/exercism/xlfe/tree/master/sum-of-multiples
- https://github.com/exercism/xperl5/tree/master/sum-of-multiples
- https://github.com/exercism/xpython/tree/master/sum-of-multiples
- https://github.com/exercism/xruby/tree/master/sum-of-multiples
- https://github.com/exercism/xswift/tree/master/sum-of-multiples

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
I'm going to need this to do a quick survey

http://x.exercism.io/problems/sum-of-multiples

* https://github.com/exercism/xclojure/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xcpp/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xcsharp/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xecmascript/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xelixir/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xerlang/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xfsharp/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xgo/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xhaskell/tree/master/sum-of-multiples
* https://github.com/exercism/xjavascript/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xlfe/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xperl5/tree/master/sum-of-multiples
* https://github.com/exercism/xpython/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xruby/tree/master/exercises/sum-of-multiples
* https://github.com/exercism/xswift/tree/master/exercises/sum-of-multiples
