### ISSUE TITLE
Extract shared inputs/outputs for exercise Trinary

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#158]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `trinary.json` containing the inputs and expected outputs for Trinary.

Trinary has been implemented in the following languages:
- https://github.com/exercism/xcoffeescript/tree/master/trinary
- https://github.com/exercism/xcpp/tree/master/trinary
- https://github.com/exercism/xcsharp/tree/master/trinary
- https://github.com/exercism/xerlang/tree/master/trinary
- https://github.com/exercism/xfsharp/tree/master/trinary
- https://github.com/exercism/xgo/tree/master/trinary
- https://github.com/exercism/xhaskell/tree/master/trinary
- https://github.com/exercism/xjava/tree/master/trinary
- https://github.com/exercism/xjavascript/tree/master/trinary
- https://github.com/exercism/xlfe/tree/master/trinary
- https://github.com/exercism/xperl5/tree/master/trinary
- https://github.com/exercism/xphp/tree/master/trinary
- https://github.com/exercism/xruby/tree/master/trinary
- https://github.com/exercism/xscala/tree/master/trinary
- https://github.com/exercism/xswift/tree/master/trinary

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by bunnymatic** [comment]
I'll try this one.

**Comment by bunnymatic** [comment]
Looks like this one is kind of on hold in hopes that instead, tracks get updated to do the `all-your-base` exercise.

**Comment by kytrinyx** [comment]
@bunnymatic Yeah, I think we'll close this one. Thanks.
