### ISSUE TITLE
Make team notifications go away once the invitation is accepted

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#16]
**Problem:** _Team invitations never go away on the notification page._ See https://github.com/exercism/exercism.io/issues/2340

---------

**Skillset:** A working knowledge of Ruby, familiarity with SQL and/or Active Record (migrations, queries).

----------

When you get invited to a team, an `Alert` gets stored in the database for your user:

```
text: "kytrinyx would like you to join the team DistributedDaemons. You can accept the invitation",
url: "/account",
link_text: "on your account page.",
```

There is no way to find this alert when someone accepts an invitation, unless we match on regex, which is a pretty terrible idea.

Instead, let's add a field to the `team_memberships` table (`TeamMembership`) to store the `inviter_id`. Then on a person's notifications page we can select all the team memberships that are not confirmed, and show a notification for it without actually storing an alert record.

To create a migration, use `rake db:generate:migration  name=the_name_of_your_migration`.

The notification controller lives in `lib/app/routes/notifications.rb` and the view is in `lib/app/views/notifications/index.erb`. There's a presenter in `lib/app/presenters/inbox.rb`.

**Comment by paulgoetze** [comment]
I will have a look at this.

**Comment by kytrinyx** [comment]
:heart:

**Comment by alex-handley** [comment]
@kytrinyx Is this being worked on? if not I can jump on it.

**Comment by kytrinyx** [comment]
@alex-handley This is all yours.

**Comment by alex-handley** [comment]
Cool, ill get started

**Comment by alex-handley** [comment]
Looks like this has actually already been fixed - https://github.com/exercism/exercism.io/pull/2374

**Comment by kytrinyx** [comment]
Aaah. Yepp, it sure has been. Thank you!
