### ISSUE TITLE
Extract shared inputs/outputs for exercise Wordy

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#163]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `wordy.json` containing the inputs and expected outputs for Wordy.

Wordy has been implemented in the following languages:

- https://github.com/exercism/xcoffeescript/tree/master/wordy
- https://github.com/exercism/xcsharp/tree/master/wordy
- https://github.com/exercism/xgo/tree/master/wordy
- https://github.com/exercism/xhaskell/tree/master/wordy
- https://github.com/exercism/xjavascript/tree/master/wordy
- https://github.com/exercism/xperl5/tree/master/wordy
- https://github.com/exercism/xphp/tree/master/wordy
- https://github.com/exercism/xpython/tree/master/wordy
- https://github.com/exercism/xruby/tree/master/wordy
- https://github.com/exercism/xscala/tree/master/wordy
- https://github.com/exercism/xswift/tree/master/wordy

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Closed by https://github.com/exercism/x-common/pull/259
