### ISSUE TITLE
Graphics: Design Beautiful Language Badges

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#166]
Problem: Nobody currently involved in exercism has graphics skills.

Solution: Maybe you're the solution!

Here's the issue that describes what we're looking for in detail:

https://github.com/exercism/exercism.io/issues/2357

**Comment by tejasbubane** [comment]
@kytrinyx I think we can close this one

**Comment by kytrinyx** [comment]
yepp, thanks!
