### ISSUE TITLE
Add optional filters to an API endpoint

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#169]
Problem: Right now if someone says `exercism fetch` on the command-line, they get the next available exercise in all 29 active languages. That's a lot of noise.

Solution: We're changing the behavior of the command so that we only fetch the exercises for tracks that you're actively working on (if you have a directory locally for that track, then we'll get the next exercise for it).

We have a workaround in the CLI right now, but we're still pulling an awful lot of data from the API. We want to change the endpoint so that it can take an optional parameter, and return a smaller response body if specific tracks are passed.

https://github.com/exercism/x-api/issues/84

**Comment by ben-biddington** [comment]
Can I reserve this one?

**Comment by kytrinyx** [comment]
For sure! Thanks.

**Comment by kytrinyx** [comment]
This was fixed in https://github.com/exercism/x-api/pull/90
