### ISSUE TITLE
Save correct filename when attempt is submitted

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#17]
**Problem:** _When submitting an exercise, we submit the path that you typed, which will depend on your working directory at the time of submitting it. Later, when we restore a solution, we restore it as if the provided path is the path relative to the language track directory._

See https://github.com/exercism/exercism.io/issues/2174 and https://github.com/exercism/cli/issues/152

-------

**Skillsets:** Basic knowledge of Ruby should be enough to get through this one.

-------

We need to store the filename that comes in as `clock.rb` not `ruby/clock/clock.rb`. There's a caveat, if files are in a subdirectory, then they need to be stored relative to the problem dir, not with just the filename.

Two tasks:

- [ ] save the correct value going forward (probably in `lib/exercism/use_cases/attempt.rb`)
- [ ] create a migration task for old data (`lib/tasks/data.rake` - this can do a simple `Submission.find_each` on all the submissions, and update the `submission.solution`).

**Comment by cypher** [comment]
I'll take this one.

**Comment by kytrinyx** [comment]
Fixed.
