### ISSUE TITLE
Add exercise-specific / language-specific inclusion to exercise READMEs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#170]
Problem: Sometimes we want language-specific hints, warnings, or instructions in an exercise README. For example, in Lua there's something that doesn't make sense in the bank account exercise, and we'd like to be able to include a small section only in the Lua README without affecting exercises in other tracks. (See https://github.com/exercism/xlua/pull/78) 

The READMEs are put together from different pieces of information, including:

- common metadata (the same across all the different language tracks)
- a language-specific "help" section (how to run the tests, where to find documentation)

This language-specific section is the same in every single exercise for that language track.

Solution: Support an optional file `HINTS.md`. If that file is in the exercise directory, then the contents will be included in the README. If not--then that's fine, no error.

See https://github.com/exercism/x-api/issues/44

**Comment by abhishekbose87** [comment]
Hi @kytrinyx, I would like to work on this issue if this has not been picked up. I will go through the codebase to understand how the READMEs are put together. Will let you know if I have questions.

**Comment by abhishekbose87** [comment]
I see there is some progress made on https://github.com/exercism/x-api/issues/44.

**Comment by kytrinyx** [comment]
Not a whole lot of progress, to be honest. It looks like it's mostly discussion, not so much code. I don't know if anyone is actively working on anything (it's worth asking there, though, if you're interested in taking a stab at it).

**Comment by abhishekbose87** [comment]
@kytrinyx This issue can be closed now after https://github.com/exercism/x-api/issues/93 got merged.

**Comment by kytrinyx** [comment]
Right, thanks!
