### ISSUE TITLE
Remove deprecated/foregone exercises from "todo" list in Problems API

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#171]
We have a large set of generic problems that can be implemented in various language tracks. For example, the `leap` problem (to determine whether or not a given year is a leap year) can be implemented in multiple languages. We're always interested in knowing, for a given track, which exercises have not yet been implemented so that we can go and add them to the track.

Problem: Some problems are _deprecated_ (we implemented them at one point, but no longer include it in the language track), and other problems are _forgeone_ (we decided that for some reason or other we should not have this problem in the track). Right now the deprecated and foregone exercises are showing up in the todo list.

Solution: filter them out.

See https://github.com/exercism/x-api/issues/88

**Comment by duffn** [comment]
I'll take this one.

**Comment by kytrinyx** [comment]
Sweet, thanks!
