### ISSUE TITLE
Put the avatar picture of the author on the code page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#173]
One day I commented on a comment not realizing that the person who commented was the same person who had submitted the code, which turned out to be a bit awkward. I realized that I use the avatar to match who says what more than I use the user names. We have the avatars for the commenters, but not for the person who submitted the original code.

This is on the page that shows a person's solution and the discussion that goes with it (`http://exercism.io/submissions/:key`, defined in `app/routes/submissions.rb`), which has a section at the top where it shows the name of the exercise and the language, and when it was submitted. It would be nice to have the avatar as part of this.

![missing-avatar](https://cloud.githubusercontent.com/assets/276834/11611714/7904f04c-9b90-11e5-8aaf-ac38c05a500f.png)

**Comment by duffn** [comment]
Are you envisioning it next to the username or somewhere else?
<img width="347" alt="screen shot 2015-12-06 at 4 14 39 pm" src="https://cloud.githubusercontent.com/assets/3457341/11616303/9d599d7c-9c34-11e5-9692-92d1ec29d351.png">

**Comment by kytrinyx** [comment]
Next to the username would work!

**Comment by duffn** [comment]
Great, I'll take this one.
