### ISSUE TITLE
Verify that nothing links to help.exercism.io

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#181]
The old help site was deprecated in December 2015. We now have content that is displayed on the main exercism.io website, under each individual language on http://exercism.io/languages.

The content itself is maintained along with the language track itself, under the `docs/` directory.

We decided on this approach since the maintainers of each individual language track are in the best position to review documentation about the language itself or the language track on Exercism.

In each language track, nothing in `docs/` directory should refer to the help.exercism.io site. It should instead point to http://exercism.io/languages/:track_id.

Also, some language tracks reference `help.exercism.io` in the SETUP.md file, which gets included into the README of every single exercise in the track.

We may also have referenced non-track-specific content that lived on help.exercism.io.  This content has probably been migrated to the [Contributing Guide of the x-common repository](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md).  If it has not been migrated, it would be a great help if you opened an issue in [x-common](https://github.com/exercism/x-common/issues) so that we can remedy the situation. If possible, please link to the old article in the [deprecated help repository](https://github.com/exercism/DEPRECATED.help.exercism.io/tree/master/app/pages).

**Comment by kytrinyx** [comment]
Note to self: next time include the link to _this_ issue in the issue that gets posted to each of the repositories. That way we'll get a visible "todo" list automatically: links back to the other repositories along with an icon that is green or red depending on the status of the issue.

**Comment by kkchu791** [comment]
Hey, this issue looks like it's been addressed. Should it be closed?

**Comment by kytrinyx** [comment]
Yay! Yes, thank you.

**Comment by kotp** [comment]
I would have closed, but no access. :(

**Comment by kytrinyx** [comment]
Ah, let me give access to the track maintainers team.

**Comment by kytrinyx** [comment]
done
