### ISSUE TITLE
Documentation: Update porting instructions

### ISSUE THREAD

**Issue by Insti** [exercism/todo#182]
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track

Says: 
> We are working on a user-friendly page on Exercism for each language track which will show the list of exercises that have not yet been implemented in the track.

I believe that this page is now in place at: 
`http://exercism.io/languages/:track_id/contribute`

for example: http://exercism.io/languages/ruby/contribute

The contributing guide should be updated to reflect this.

**Comment by Cohen-Carlisle** [comment]
Closed via https://github.com/exercism/x-common/pull/307
