### ISSUE TITLE
Add missing test to sum-of-multiples

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#20]
See https://github.com/exercism/exercism.io/issues/2486 for the original issue.

The _Sum of Multiples_ exercise has the potential to be very confusing. The problem is defined in such a way that you might have one or more factors. If a number is a multiple of more than one factor, then it should only be counted once in the sum.

We should add another test case that sums (the default factors 3 and 5) all the way to 100, and it should be placed right after the test that sums multiples of 3 and 5 up to 10.

**Comment by abeger** [comment]
As someone who just tried to solve it, I vote that it's still pretty confusing. I took a stab at making it clearer in exercism/x-common#157

**Comment by kytrinyx** [comment]
Thanks!

**Comment by petertseng** [comment]
All tracks have completed this!
