### ISSUE TITLE
Add missing test to Sum of Multiples exercise in C++

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#51]
See https://github.com/exercism/todo/issues/20

------

Add a test case that sums the default factors (3 and 5) all the way to 100.

Place this test right after the one that sums multiples of 3 and 5 up to 10.

The repository is here: https://github.com/exercism/xcpp

**Comment by duffn** [comment]
Sorry, I used incorrect wording in my PR to close automatically. Please close.

**Comment by kytrinyx** [comment]
Ah, nice. Thank you!
