### ISSUE TITLE
Add missing test to Sum of Multiples exercise in Haskell

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#57]
See https://github.com/exercism/todo/issues/20

------

Add a test case that sums the default factors (3 and 5) all the way to 100.

Place this test right after the one that sums multiples of 3 and 5 up to 10.

The repository is here: https://github.com/exercism/xhaskell

**Comment by petertseng** [comment]
Done by https://github.com/exercism/xhaskell/pull/87 and https://github.com/exercism/xhaskell/pull/152
