### ISSUE TITLE
Extract shared inputs/outputs for exercise Accumulate

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#64]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `accumulate.json` containing the inputs and expected outputs for Accumulate.

Accumulate has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/accumulate
- https://github.com/exercism/xcoffeescript/tree/master/accumulate
- https://github.com/exercism/xcsharp/tree/master/accumulate
- https://github.com/exercism/xerlang/tree/master/accumulate
- https://github.com/exercism/xfsharp/tree/master/accumulate
- https://github.com/exercism/xhaskell/tree/master/accumulate
- https://github.com/exercism/xjava/tree/master/accumulate
- https://github.com/exercism/xjavascript/tree/master/accumulate
- https://github.com/exercism/xlfe/tree/master/accumulate
- https://github.com/exercism/xperl5/tree/master/accumulate
- https://github.com/exercism/xruby/tree/master/accumulate
- https://github.com/exercism/xscala/tree/master/accumulate
- https://github.com/exercism/xswift/tree/master/accumulate

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by abeger** [comment]
This one is tricky, given that each test case's implementation is incredibly language-specific. I think the best we can do is use the JSON to describe the tests that someone should implement, rather than try to figure out how to generate the test file.

**Comment by kytrinyx** [comment]
Let's just skip this one. We've been talking about deprecating it in favor of the more interesting `list-ops` problem.

**Comment by abeger** [comment]
After looking a little longer, I'll happily endorse deprecation. This is just a weird one. Thanks!

**Comment by kytrinyx** [comment]
Agreed, and thanks for taking the time to think about it!
