### ISSUE TITLE
Extract shared inputs/outputs for exercise Acronym

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#65]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `acronym.json` containing the inputs and expected outputs for Acronym.

Acronym has been implemented in the following languages:

- https://github.com/exercism/xcsharp/tree/master/acronym
- https://github.com/exercism/xfsharp/tree/master/acronym
- https://github.com/exercism/xruby/tree/master/acronym
- https://github.com/exercism/xswift/tree/master/acronym

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by abeger** [comment]
Done and done.

**Comment by kytrinyx** [comment]
Sweet, thanks!
