### ISSUE TITLE
Extract shared inputs/outputs for exercise Allergies

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#66]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `allergies.json` containing the inputs and expected outputs for Allergies.

Allergies has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/allergies
- https://github.com/exercism/xcsharp/tree/master/allergies
- https://github.com/exercism/xelisp/tree/master/allergies
- https://github.com/exercism/xelixir/tree/master/allergies
- https://github.com/exercism/xerlang/tree/master/allergies
- https://github.com/exercism/xfsharp/tree/master/allergies
- https://github.com/exercism/xgo/tree/master/allergies
- https://github.com/exercism/xhaskell/tree/master/allergies
- https://github.com/exercism/xjava/tree/master/allergies
- https://github.com/exercism/xjavascript/tree/master/allergies
- https://github.com/exercism/xlfe/tree/master/allergies
- https://github.com/exercism/xlisp/tree/master/allergies
- https://github.com/exercism/xperl5/tree/master/allergies
- https://github.com/exercism/xpython/tree/master/allergies
- https://github.com/exercism/xruby/tree/master/allergies
- https://github.com/exercism/xrust/tree/master/allergies
- https://github.com/exercism/xscala/tree/master/allergies
- https://github.com/exercism/xswift/tree/master/allergies

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by abeger** [comment]
Pull request above.

**Comment by petertseng** [comment]
Good to close since the PR already-linked is merged
