### ISSUE TITLE
Extract shared inputs/outputs for exercise Anagram

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#68]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `anagram.json` containing the inputs and expected outputs for Anagram.

Anagram has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/anagram
- https://github.com/exercism/xcoffeescript/tree/master/anagram
- https://github.com/exercism/xcpp/tree/master/anagram
- https://github.com/exercism/xcsharp/tree/master/anagram
- https://github.com/exercism/xecmascript/tree/master/anagram
- https://github.com/exercism/xelisp/tree/master/anagram
- https://github.com/exercism/xelixir/tree/master/anagram
- https://github.com/exercism/xerlang/tree/master/anagram
- https://github.com/exercism/xfsharp/tree/master/anagram
- https://github.com/exercism/xgo/tree/master/anagram
- https://github.com/exercism/xhaskell/tree/master/anagram
- https://github.com/exercism/xjava/tree/master/anagram
- https://github.com/exercism/xjavascript/tree/master/anagram
- https://github.com/exercism/xlfe/tree/master/anagram
- https://github.com/exercism/xlisp/tree/master/anagram
- https://github.com/exercism/xlua/tree/master/anagram
- https://github.com/exercism/xobjective-c/tree/master/anagram
- https://github.com/exercism/xocaml/tree/master/anagram
- https://github.com/exercism/xperl5/tree/master/anagram
- https://github.com/exercism/xpython/tree/master/anagram
- https://github.com/exercism/xruby/tree/master/anagram
- https://github.com/exercism/xrust/tree/master/anagram
- https://github.com/exercism/xscala/tree/master/anagram
- https://github.com/exercism/xscheme/tree/master/anagram
- https://github.com/exercism/xswift/tree/master/anagram

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Good to merge since the already-linked PR is merged
