### ISSUE TITLE
Extract shared inputs/outputs for exercise Atbash Cipher

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#69]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `atbash-cipher.json` containing the inputs and expected outputs for Atbash Cipher.

Atbash Cipher has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/atbash-cipher
- https://github.com/exercism/xcoffeescript/tree/master/atbash-cipher
- https://github.com/exercism/xcsharp/tree/master/atbash-cipher
- https://github.com/exercism/xelixir/tree/master/atbash-cipher
- https://github.com/exercism/xerlang/tree/master/atbash-cipher
- https://github.com/exercism/xfsharp/tree/master/atbash-cipher
- https://github.com/exercism/xgo/tree/master/atbash-cipher
- https://github.com/exercism/xhaskell/tree/master/atbash-cipher
- https://github.com/exercism/xjava/tree/master/atbash-cipher
- https://github.com/exercism/xjavascript/tree/master/atbash-cipher
- https://github.com/exercism/xlfe/tree/master/atbash-cipher
- https://github.com/exercism/xlisp/tree/master/atbash-cipher
- https://github.com/exercism/xperl5/tree/master/atbash-cipher
- https://github.com/exercism/xpython/tree/master/atbash-cipher
- https://github.com/exercism/xruby/tree/master/atbash-cipher
- https://github.com/exercism/xscala/tree/master/atbash-cipher
- https://github.com/exercism/xswift/tree/master/atbash-cipher

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by abeger** [comment]
PIcking this up

**Comment by abeger** [comment]
Some notes on these tests:

* All suites implemented tests for `encode()`, but only Erlang, Java, perl5, and Python implemented tests for `decode()`. The encode-only tests could stay that way using this JSON, but I think testing both ways is nicer.
* The List Flavored Erlang tests are entirely different for no discernible reason. I dropped them in favor of the majority's tests.

**Comment by kytrinyx** [comment]
Excellent. I would be curious to hear what the folks in the LFE track think about this problem, I bet they had good reasons for what they chose to do (they usually do).

@exercism/lisp Apparently Bengt Kleberg wrote the code for that, but I don't know his GitHub username. Do any of you remember the discussion about this from back when it was implemented?

**Comment by yurrriq** [comment]
Re: LFE.

Wow, you're quite right. There's no good reason for the difference. The only one I can think of is maybe I had a stale version when I ported the Erlang tests...

I'll update xlfe when a chance.

**Comment by kytrinyx** [comment]
OK, cool! Yeah, I bet there was a stale version out there. Things have been moving quickly these past few months.

**Comment by yurrriq** [comment]
:tada: exercism/xlfe@3bf9eff6b73f99d8707740b3d94b8cf64e6d595c

**Comment by kytrinyx** [comment]
winning :)
