### ISSUE TITLE
Extract shared inputs/outputs for exercise Beer Song

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#71]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `beer-song.json` containing the inputs and expected outputs for Beer Song.

Beer Song has been implemented in the following languages:
- https://github.com/exercism/xclojure/tree/master/beer-song
- https://github.com/exercism/xcoffeescript/tree/master/beer-song
- https://github.com/exercism/xcpp/tree/master/beer-song
- https://github.com/exercism/xecmascript/tree/master/beer-song
- https://github.com/exercism/xerlang/tree/master/beer-song
- https://github.com/exercism/xfsharp/tree/master/beer-song
- https://github.com/exercism/xgo/tree/master/beer-song
- https://github.com/exercism/xhaskell/tree/master/beer-song
- https://github.com/exercism/xjavascript/tree/master/beer-song
- https://github.com/exercism/xlfe/tree/master/beer-song
- https://github.com/exercism/xlisp/tree/master/beer-song
- https://github.com/exercism/xlua/tree/master/beer-song
- https://github.com/exercism/xocaml/tree/master/beer-song
- https://github.com/exercism/xperl5/tree/master/beer-song
- https://github.com/exercism/xpython/tree/master/beer-song
- https://github.com/exercism/xruby/tree/master/beer-song
- https://github.com/exercism/xrust/tree/master/beer-song

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by bunnymatic** [comment]
I'll try this one.
