### ISSUE TITLE
Extract shared inputs/outputs for exercise Binary Search

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#73]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `binary-search.json` containing the inputs and expected outputs for Binary Search.

Binary Search has been implemented in the following languages:

- https://github.com/exercism/xgo/tree/master/binary-search
- https://github.com/exercism/xjavascript/tree/master/binary-search
- https://github.com/exercism/xperl5/tree/master/binary-search
- https://github.com/exercism/xruby/tree/master/binary-search

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
completed in https://github.com/exercism/x-common/pull/349
