### ISSUE TITLE
Extract shared inputs/outputs for exercise Binary

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#74]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `binary.json` containing the inputs and expected outputs for Binary.

Binary has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/binary
- https://github.com/exercism/xcoffeescript/tree/master/binary
- https://github.com/exercism/xcpp/tree/master/binary
- https://github.com/exercism/xcsharp/tree/master/binary
- https://github.com/exercism/xelisp/tree/master/binary
- https://github.com/exercism/xelixir/tree/master/binary
- https://github.com/exercism/xerlang/tree/master/binary
- https://github.com/exercism/xfsharp/tree/master/binary
- https://github.com/exercism/xgo/tree/master/binary
- https://github.com/exercism/xhaskell/tree/master/binary
- https://github.com/exercism/xjava/tree/master/binary
- https://github.com/exercism/xjavascript/tree/master/binary
- https://github.com/exercism/xlfe/tree/master/binary
- https://github.com/exercism/xlisp/tree/master/binary
- https://github.com/exercism/xlua/tree/master/binary
- https://github.com/exercism/xplsql/tree/master/binary
- https://github.com/exercism/xpython/tree/master/binary
- https://github.com/exercism/xruby/tree/master/binary
- https://github.com/exercism/xscala/tree/master/binary
- https://github.com/exercism/xswift/tree/master/binary

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Closed by https://github.com/exercism/x-common/pull/296
