### ISSUE TITLE
Extract shared inputs/outputs for exercise Bowling

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#76]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `bowling.json` containing the inputs and expected outputs for Bowling.

Bowling has been implemented in the following languages:

- https://github.com/exercism/xphp/tree/master/bowling

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Note, in flight at https://github.com/exercism/x-common/pull/240

**Comment by petertseng** [comment]
Good to close

**Comment by kytrinyx** [comment]
Thanks.
