### ISSUE TITLE
Extract shared inputs/outputs for exercise Bracket Push

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#77]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `bracket-push.json` containing the inputs and expected outputs for Bracket Push.

Bracket Push has been implemented in the following languages:

- https://github.com/exercism/xgo/tree/master/bracket-push
- https://github.com/exercism/xjavascript/tree/master/bracket-push

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Closed by https://github.com/exercism/x-common/pull/237
