### ISSUE TITLE
Extract shared inputs/outputs for exercise Change

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#78]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `change.json` containing the inputs and expected outputs for Change.

Change has been implemented in the following languages:

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Closed by https://github.com/exercism/x-common/pull/249
