### ISSUE TITLE
Extract shared inputs/outputs for exercise Circular Buffer

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#79]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `circular-buffer.json` containing the inputs and expected outputs for Circular Buffer.

Circular Buffer has been implemented in the following languages:
- https://github.com/exercism/xerlang/tree/master/circular-buffer
- https://github.com/exercism/xgo/tree/master/circular-buffer
- https://github.com/exercism/xjavascript/tree/master/circular-buffer
- https://github.com/exercism/xlfe/tree/master/circular-buffer
- https://github.com/exercism/xlua/tree/master/circular-buffer
- https://github.com/exercism/xruby/tree/master/circular-buffer
- https://github.com/exercism/xrust/tree/master/circular-buffer

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
I would say "no, silly! my fork of x-common isn't sufficient to close this issue!" and reopen, but I imagine that if I reopen I will again accidentally close it sometime soon...
