### ISSUE TITLE
Extract shared inputs/outputs for exercise Connect

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#81]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `connect.json` containing the inputs and expected outputs for Connect.

Connect has been implemented in the following languages:

- https://github.com/exercism/xgo/tree/master/connect
- https://github.com/exercism/xhaskell/tree/master/connect
- https://github.com/exercism/xphp/tree/master/connect
- https://github.com/exercism/xscala/tree/master/connect

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
closed by https://github.com/exercism/x-common/pull/297
