### ISSUE TITLE
Extract shared inputs/outputs for exercise Counter

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#82]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `counter.json` containing the inputs and expected outputs for Counter.

Counter has been implemented in the following languages:

- https://github.com/exercism/xgo/tree/master/counter

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Counter will be deprecated so no need to add test data for it. https://github.com/exercism/x-common/issues/383
