### ISSUE TITLE
Extract shared inputs/outputs for exercise Crypto Square

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#83]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `crypto-square.json` containing the inputs and expected outputs for Crypto Square.

Crypto Square has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/crypto-square
- https://github.com/exercism/xcpp/tree/master/crypto-square
- https://github.com/exercism/xcsharp/tree/master/crypto-square
- https://github.com/exercism/xfsharp/tree/master/crypto-square
- https://github.com/exercism/xgo/tree/master/crypto-square
- https://github.com/exercism/xhaskell/tree/master/crypto-square
- https://github.com/exercism/xjava/tree/master/crypto-square
- https://github.com/exercism/xjavascript/tree/master/crypto-square
- https://github.com/exercism/xperl5/tree/master/crypto-square
- https://github.com/exercism/xpython/tree/master/crypto-square
- https://github.com/exercism/xruby/tree/master/crypto-square
- https://github.com/exercism/xscala/tree/master/crypto-square
- https://github.com/exercism/xswift/tree/master/crypto-square

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Closed by https://github.com/exercism/x-common/pull/250
