### ISSUE TITLE
Extract shared inputs/outputs for exercise Difference Of Squares

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#85]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `difference-of-squares.json` containing the inputs and expected outputs for Difference Of Squares.

Difference Of Squares has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/difference-of-squares
- https://github.com/exercism/xcpp/tree/master/difference-of-squares
- https://github.com/exercism/xcsharp/tree/master/difference-of-squares
- https://github.com/exercism/xelisp/tree/master/difference-of-squares
- https://github.com/exercism/xelixir/tree/master/difference-of-squares
- https://github.com/exercism/xerlang/tree/master/difference-of-squares
- https://github.com/exercism/xfsharp/tree/master/difference-of-squares
- https://github.com/exercism/xgo/tree/master/difference-of-squares
- https://github.com/exercism/xhaskell/tree/master/difference-of-squares
- https://github.com/exercism/xjavascript/tree/master/difference-of-squares
- https://github.com/exercism/xlfe/tree/master/difference-of-squares
- https://github.com/exercism/xlisp/tree/master/difference-of-squares
- https://github.com/exercism/xperl5/tree/master/difference-of-squares
- https://github.com/exercism/xphp/tree/master/difference-of-squares
- https://github.com/exercism/xplsql/tree/master/difference-of-squares
- https://github.com/exercism/xpython/tree/master/difference-of-squares
- https://github.com/exercism/xruby/tree/master/difference-of-squares
- https://github.com/exercism/xrust/tree/master/difference-of-squares
- https://github.com/exercism/xscala/tree/master/difference-of-squares
- https://github.com/exercism/xscheme/tree/master/difference-of-squares
- https://github.com/exercism/xswift/tree/master/difference-of-squares

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by abeger** [comment]
Tackling this one now

**Comment by kytrinyx** [comment]
:+1:

**Comment by petertseng** [comment]
Good to close now, because of https://github.com/exercism/x-common/pull/146
