### ISSUE TITLE
Extract shared inputs/outputs for exercise Etl

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#90]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `etl.json` containing the inputs and expected outputs for Etl.

Etl has been implemented in the following languages:
- https://github.com/exercism/xclojure/tree/master/etl
- https://github.com/exercism/xcpp/tree/master/etl
- https://github.com/exercism/xcsharp/tree/master/etl
- https://github.com/exercism/xecmascript/tree/master/etl
- https://github.com/exercism/xelixir/tree/master/etl
- https://github.com/exercism/xerlang/tree/master/etl
- https://github.com/exercism/xfsharp/tree/master/etl
- https://github.com/exercism/xgo/tree/master/etl
- https://github.com/exercism/xhaskell/tree/master/etl
- https://github.com/exercism/xjava/tree/master/etl
- https://github.com/exercism/xjavascript/tree/master/etl
- https://github.com/exercism/xlfe/tree/master/etl
- https://github.com/exercism/xlisp/tree/master/etl
- https://github.com/exercism/xobjective-c/tree/master/etl
- https://github.com/exercism/xperl5/tree/master/etl
- https://github.com/exercism/xpython/tree/master/etl
- https://github.com/exercism/xruby/tree/master/etl
- https://github.com/exercism/xrust/tree/master/etl
- https://github.com/exercism/xscala/tree/master/etl
- https://github.com/exercism/xswift/tree/master/etl

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by bunnymatic** [comment]
I'm working on this one.

**Comment by bunnymatic** [comment]
https://github.com/exercism/x-common/pull/507
