### ISSUE TITLE
Extract shared inputs/outputs for exercise Grains

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#96]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `grains.json` containing the inputs and expected outputs for Grains.

Grains has been implemented in the following languages:
- https://github.com/exercism/xclojure/tree/master/grains
- https://github.com/exercism/xcpp/tree/master/grains
- https://github.com/exercism/xecmascript/tree/master/grains
- https://github.com/exercism/xelixir/tree/master/grains
- https://github.com/exercism/xerlang/tree/master/grains
- https://github.com/exercism/xfsharp/tree/master/grains
- https://github.com/exercism/xgo/tree/master/grains
- https://github.com/exercism/xhaskell/tree/master/grains
- https://github.com/exercism/xjavascript/tree/master/grains
- https://github.com/exercism/xlfe/tree/master/grains
- https://github.com/exercism/xlisp/tree/master/grains
- https://github.com/exercism/xlua/tree/master/grains
- https://github.com/exercism/xperl5/tree/master/grains
- https://github.com/exercism/xplsql/tree/master/grains
- https://github.com/exercism/xpython/tree/master/grains
- https://github.com/exercism/xruby/tree/master/grains
- https://github.com/exercism/xscala/tree/master/grains
- https://github.com/exercism/xscheme/tree/master/grains
- https://github.com/exercism/xswift/tree/master/grains

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by petertseng** [comment]
Closed by linked PR.
